"""
Feedback Handler for Human-in-the-Loop Learning
================================================
Handles manual approval and memory updates for the RAG system.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Dict, List, Optional
from pathlib import Path
import json

import sys
sys.path.insert(0, str(Path(__file__).parent.parent))

from tid_collections.hafiza_collection import HafizaCollection


@dataclass
class TranslationFeedback:
    """Represents a translation with its feedback status."""
    transkripsiyon: str
    generated_translation: str
    corrected_translation: Optional[str] = None
    is_approved: bool = False
    provider: str = "unknown"
    confidence: float = 0.0
    feedback_notes: str = ""
    timestamp: str = ""
    
    def __post_init__(self):
        if not self.timestamp:
            self.timestamp = datetime.now().isoformat()


class FeedbackHandler:
    """
    Handles the human-in-the-loop feedback process.
    
    Workflow:
    1. Translation is generated by LLM
    2. Human reviews and optionally corrects
    3. Approved translation is saved to memory
    """
    
    def __init__(self, hafiza: Optional[HafizaCollection] = None):
        """
        Initialize the feedback handler.
        
        Args:
            hafiza: Optional pre-initialized HafizaCollection
        """
        self.hafiza = hafiza or HafizaCollection()
        self._pending_feedback: Dict[str, TranslationFeedback] = {}
    
    def create_feedback(
        self,
        transkripsiyon: str,
        generated_translation: str,
        provider: str = "unknown",
        confidence: float = 0.0,
    ) -> str:
        """
        Create a new feedback entry for review.
        
        Args:
            transkripsiyon: The original TID transcription
            generated_translation: The LLM-generated translation
            provider: The LLM provider used
            confidence: The LLM confidence score
            
        Returns:
            Feedback ID for tracking
        """
        import uuid
        feedback_id = f"fb_{uuid.uuid4().hex[:12]}"
        
        feedback = TranslationFeedback(
            transkripsiyon=transkripsiyon.upper(),
            generated_translation=generated_translation,
            provider=provider,
            confidence=confidence,
        )
        
        self._pending_feedback[feedback_id] = feedback
        return feedback_id
    
    def approve_translation(
        self,
        feedback_id: str,
        corrected_translation: Optional[str] = None,
        notes: str = "",
    ) -> Optional[str]:
        """
        Approve a translation and save to memory.
        
        Args:
            feedback_id: The feedback ID from create_feedback
            corrected_translation: Optional corrected version (uses original if None)
            notes: Optional feedback notes
            
        Returns:
            Hafiza document ID if saved, None if feedback not found
        """
        feedback = self._pending_feedback.get(feedback_id)
        if not feedback:
            return None
        
        # Use corrected or original translation
        final_translation = corrected_translation or feedback.generated_translation
        
        # Update feedback status
        feedback.corrected_translation = corrected_translation
        feedback.is_approved = True
        feedback.feedback_notes = notes
        
        # Save to hafiza
        doc_id = self.hafiza.add_translation(
            transkripsiyon=feedback.transkripsiyon,
            ceviri=final_translation,
            provider=feedback.provider,
            confidence=feedback.confidence if not corrected_translation else 1.0,
        )
        
        # Remove from pending
        del self._pending_feedback[feedback_id]
        
        return doc_id
    
    def reject_translation(self, feedback_id: str, reason: str = "") -> bool:
        """
        Reject a translation (don't save to memory).
        
        Args:
            feedback_id: The feedback ID
            reason: Optional reason for rejection
            
        Returns:
            True if rejection was processed
        """
        if feedback_id in self._pending_feedback:
            feedback = self._pending_feedback[feedback_id]
            feedback.feedback_notes = f"Rejected: {reason}"
            del self._pending_feedback[feedback_id]
            return True
        return False
    
    def get_pending(self) -> List[Dict]:
        """Get all pending feedback entries."""
        return [
            {
                "id": fid,
                "transkripsiyon": fb.transkripsiyon,
                "generated_translation": fb.generated_translation,
                "provider": fb.provider,
                "confidence": fb.confidence,
                "timestamp": fb.timestamp,
            }
            for fid, fb in self._pending_feedback.items()
        ]
    
    def get_hafiza_stats(self) -> Dict:
        """Get statistics about the hafiza collection."""
        return {
            "total_translations": self.hafiza.get_count(),
            "pending_reviews": len(self._pending_feedback),
        }
    
    def add_direct_translation(
        self,
        transkripsiyon: str,
        ceviri: str,
        provider: str = "manual",
    ) -> str:
        """
        Directly add a translation to memory (bypass review).
        Useful for importing known-good translations.
        
        Args:
            transkripsiyon: The TID transcription
            ceviri: The verified translation
            provider: The source (default "manual")
            
        Returns:
            Hafiza document ID
        """
        return self.hafiza.add_translation(
            transkripsiyon=transkripsiyon.upper(),
            ceviri=ceviri,
            provider=provider,
            confidence=1.0,
        )
    
    def search_similar(self, transkripsiyon: str, top_k: int = 5) -> List[Dict]:
        """
        Search for similar translations in memory.
        
        Args:
            transkripsiyon: The transcription to search for
            top_k: Number of results
            
        Returns:
            List of similar translations
        """
        return self.hafiza.query(transkripsiyon, n_results=top_k)


if __name__ == "__main__":
    # Test the feedback handler
    print("Testing Feedback Handler...")
    print("=" * 60)
    
    handler = FeedbackHandler()
    stats = handler.get_hafiza_stats()
    print(f"Hafiza translations: {stats['total_translations']}")
    
    # Create a feedback entry
    feedback_id = handler.create_feedback(
        transkripsiyon="TEST CEVIRI YAPMAK",
        generated_translation="Test cevirisi yapildi.",
        provider="test",
        confidence=0.85,
    )
    print(f"\nCreated feedback: {feedback_id}")
    print(f"Pending: {len(handler.get_pending())}")
    
    # Approve it
    doc_id = handler.approve_translation(
        feedback_id,
        corrected_translation="Test cevirisi yapilmistir.",
        notes="Zaman eki duzeltildi",
    )
    print(f"Approved and saved: {doc_id}")
    print(f"Pending after approval: {len(handler.get_pending())}")
    
    # Check new stats
    stats = handler.get_hafiza_stats()
    print(f"Hafiza translations after: {stats['total_translations']}")
